import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf4',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dbe9ff',
        'surface-container-highest': '#d3e4fd',
        'on-surface': '#0b1c2e',
        'on-surface-variant': '#42474f',
        'inverse-surface': '#213144',
        'inverse-on-surface': '#eaf1ff',
        'outline': '#727780',
        'outline-variant': '#c2c7d0',
        primary: '#0f4573',
        'primary-container': '#2f5d8c',
        'inverse-primary': '#9fcaff',
        secondary: '#7b5900',
        'secondary-container': '#fcca66',
        tertiary: '#5a3e00',
        'tertiary-container': '#785403',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        ivory: '#FAF7F0',
        paper: '#FFFFFF',
        'legal-border': '#E5DDCF',
        'legal-ai': '#F3EFE6',
        'accent-gold': '#C89B3C',
        'risk-high-bg': '#ffdad6',
        'risk-high-text': '#93000a',
        'risk-medium-bg': '#ffdeaa',
        'risk-medium-text': '#5a3e00',
        'risk-low-bg': '#e5eeff',
        'risk-low-text': '#0f4573',
        'risk-critical-bg': '#fee2e2',
        'risk-critical-text': '#991b1b',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'Segoe UI', 'Arial', 'sans-serif'],
        legal: ['Inter', 'ui-sans-serif', 'system-ui', 'Segoe UI', 'Arial', 'sans-serif'],
        domine: ['Domine', 'Georgia', 'Cambria', 'Times New Roman', 'serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      boxShadow: {
        paper: '0 4px 10px rgba(11, 28, 46, 0.05)',
        raised: '0 18px 38px rgba(11, 28, 46, 0.12)',
        navy: '0 12px 30px rgba(15, 69, 115, 0.22)',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        '2xl': '64px',
        gutter: '24px',
        margin: '32px',
      },
    },
  },
  plugins: [],
};

export default config;
