from __future__ import annotations

from enum import Enum


class LegalQueryIntent(str, Enum):
    STUDENT_RENTAL_CONTRACT_REVIEW = "STUDENT_RENTAL_CONTRACT_REVIEW"
    PART_TIME_OR_INTERNSHIP_CONTRACT_REVIEW = "PART_TIME_OR_INTERNSHIP_CONTRACT_REVIEW"
    SMALL_SERVICE_CONTRACT_REVIEW = "SMALL_SERVICE_CONTRACT_REVIEW"
    SMALL_SALE_CONTRACT_REVIEW = "SMALL_SALE_CONTRACT_REVIEW"
    PERSONAL_LOAN_NOTE_REVIEW = "PERSONAL_LOAN_NOTE_REVIEW"
    CONTRACT_SUMMARY = "CONTRACT_SUMMARY"
    CONTRACT_RISK_ANALYSIS = "CONTRACT_RISK_ANALYSIS"
    CLAUSE_ANALYSIS = "CLAUSE_ANALYSIS"
    MISSING_CLAUSE_CHECK = "MISSING_CLAUSE_CHECK"
    CLAUSE_REVISION = "CLAUSE_REVISION"
    CLAUSE_DRAFTING = "CLAUSE_DRAFTING"
    SIGNING_DECISION_SUPPORT = "SIGNING_DECISION_SUPPORT"
    CONTRACT_INFORMATION_EXTRACTION = "CONTRACT_INFORMATION_EXTRACTION"
    LEGAL_KB_QUESTION = "LEGAL_KB_QUESTION"
    UNDER_SPECIFIED_LEGAL_QUERY = "UNDER_SPECIFIED_LEGAL_QUERY"
    INVALID_OR_MEANINGLESS_QUERY = "INVALID_OR_MEANINGLESS_QUERY"
    UNKNOWN_USER_ROLE = "UNKNOWN_USER_ROLE"
    UNKNOWN_JURISDICTION = "UNKNOWN_JURISDICTION"
    INCOMPLETE_DOCUMENT = "INCOMPLETE_DOCUMENT"
    OUT_OF_DOMAIN_GENERAL_QUERY = "OUT_OF_DOMAIN_GENERAL_QUERY"
    LEGAL_BUT_NOT_CONTRACT_SCOPE = "LEGAL_BUT_NOT_CONTRACT_SCOPE"
    CONTRACT_TYPE_OUT_OF_STUDENT_SCOPE = "CONTRACT_TYPE_OUT_OF_STUDENT_SCOPE"
    FOREIGN_LAW_QUERY = "FOREIGN_LAW_QUERY"
    NO_RELEVANT_DOCUMENT_FOUND = "NO_RELEVANT_DOCUMENT_FOUND"
    LOW_RETRIEVAL_CONFIDENCE = "LOW_RETRIEVAL_CONFIDENCE"
    PARTIAL_KB_COVERAGE = "PARTIAL_KB_COVERAGE"
    OUTDATED_KNOWLEDGE_BASE = "OUTDATED_KNOWLEDGE_BASE"
    CONFLICTING_REFERENCES = "CONFLICTING_REFERENCES"
    INSUFFICIENT_FACTS = "INSUFFICIENT_FACTS"
    PROMPT_INJECTION_OR_POLICY_BYPASS = "PROMPT_INJECTION_OR_POLICY_BYPASS"
    UNSAFE_LEGAL_REQUEST = "UNSAFE_LEGAL_REQUEST"
    OVERCONFIDENT_LEGAL_CONCLUSION_REQUEST = "OVERCONFIDENT_LEGAL_CONCLUSION_REQUEST"


class ContractType(str, Enum):
    STUDENT_RENTAL = "STUDENT_RENTAL"
    PART_TIME_OR_INTERNSHIP = "PART_TIME_OR_INTERNSHIP"
    SMALL_SERVICE_OR_FREELANCE = "SMALL_SERVICE_OR_FREELANCE"
    SMALL_ASSET_SALE = "SMALL_ASSET_SALE"
    PERSONAL_LOAN_SIMPLE = "PERSONAL_LOAN_SIMPLE"
    OUT_OF_STUDENT_SCOPE = "OUT_OF_STUDENT_SCOPE"
    UNKNOWN = "UNKNOWN"


class UserRole(str, Enum):
    PARTY_A = "PARTY_A"
    PARTY_B = "PARTY_B"
    TENANT = "TENANT"
    LANDLORD = "LANDLORD"
    BORROWER = "BORROWER"
    LENDER = "LENDER"
    UNKNOWN = "UNKNOWN"


class Jurisdiction(str, Enum):
    VIETNAM = "VIETNAM"
    FOREIGN = "FOREIGN"
    UNKNOWN = "UNKNOWN"


class ResponseStatus(str, Enum):
    ANSWERABLE = "ANSWERABLE"
    PARTIALLY_ANSWERABLE = "PARTIALLY_ANSWERABLE"
    NEED_MORE_INFORMATION = "NEED_MORE_INFORMATION"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    OUT_OF_KNOWLEDGE_BASE = "OUT_OF_KNOWLEDGE_BASE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    INCOMPLETE_INPUT = "INCOMPLETE_INPUT"
    HIGH_RISK_REQUIRE_LAWYER = "HIGH_RISK_REQUIRE_LAWYER"
    UNSAFE_REQUEST = "UNSAFE_REQUEST"


class ResponseMode(str, Enum):
    DIRECT_ANSWER = "DIRECT_ANSWER"
    DOCUMENT_BASED_ANALYSIS = "DOCUMENT_BASED_ANALYSIS"
    ASK_FOR_INFORMATION = "ASK_FOR_INFORMATION"
    SAFE_REDIRECT = "SAFE_REDIRECT"
    REFUSAL = "REFUSAL"
    LAWYER_ESCALATION = "LAWYER_ESCALATION"


class RiskLevel(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"


class SuggestionType(str, Enum):
    DIRECT_ANSWER = "DIRECT_ANSWER"
    ASK_UPLOAD_CONTRACT = "ASK_UPLOAD_CONTRACT"
    ASK_CONTRACT_TYPE = "ASK_CONTRACT_TYPE"
    ASK_USER_ROLE = "ASK_USER_ROLE"
    ASK_TARGET_CLAUSE = "ASK_TARGET_CLAUSE"
    ASK_MORE_FACTS = "ASK_MORE_FACTS"
    SUGGEST_REVISE_CLAUSE = "SUGGEST_REVISE_CLAUSE"
    SUGGEST_NEGOTIATION = "SUGGEST_NEGOTIATION"
    SUGGEST_LAWYER = "SUGGEST_LAWYER"
    REDIRECT_TO_SUPPORTED_SCOPE = "REDIRECT_TO_SUPPORTED_SCOPE"
    REFUSE_AND_REDIRECT = "REFUSE_AND_REDIRECT"
