import { ArrowLeft, Download } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Badge } from "../../components/common/Badge";
import { Button } from "../../components/common/Button";
import { Card } from "../../components/common/Card";
import { DataTable, type DataTableColumn } from "../../components/common/DataTable";
import { PageHeader } from "../../components/common/PageHeader";
import { API_ENDPOINTS } from "../../config/api";
import { useToast } from "../../hooks/useToast";
import { createRevenueAdjustment, downloadRevenueExport, getAdminStatement, getExpertStatement, markStatementPaid, markStatementPaymentPending } from "../../services/revenuePayroll.service";
import type { RevenueAdjustment, RevenueStatement, RevenueStatementItem } from "../../types/expertRevenue";
import { formatVndCurrency } from "../../utils/format";

export function RevenueStatementDetailPage({admin=false}:{admin?:boolean}){const {statementId=""}=useParams();const toast=useToast();const [data,setData]=useState<RevenueStatement|null>(null);const load=useCallback(async()=>{try{setData(await (admin?getAdminStatement(statementId):getExpertStatement(statementId)));}catch(e){toast.error(e instanceof Error?e.message:"Không thể tải statement");}},[admin,statementId,toast]);useEffect(()=>{void load();},[load]);
 const items=useMemo<DataTableColumn<RevenueStatementItem>[]>(()=>[{header:"Ticket",cell:i=><Link className="text-primary" to={admin?`/admin/tickets/${i.ticketId}`:`/lawyer/tickets/${i.ticketId}`}>{i.ticketCode}</Link>},{header:"Phí tư vấn",cell:i=>money(i.consultationFee)},{header:"Hoa hồng",cell:i=>`${(i.commissionRateSnapshot*100).toFixed(2)}%`},{header:"Phí nền tảng",cell:i=>money(i.platformFee)},{header:"Chuyên gia nhận",cell:i=>money(i.expertPayout)},{header:"Ghi nhận",cell:i=>new Date(i.recognizedAt).toLocaleString("vi-VN")}], [admin]);
 const adjustments=useMemo<DataTableColumn<RevenueAdjustment>[]>(()=>[{header:"Loại",cell:a=>a.type},{header:"Số tiền",cell:a=>money(a.amount)},{header:"Lý do",cell:a=>a.reason},{header:"Thời gian",cell:a=>new Date(a.createdAt).toLocaleString("vi-VN")}],[]);
 if(!data)return <p className="p-lg">Đang tải...</p>;const exportUrl=admin?`${API_ENDPOINTS.adminRevenue.period(data.period.id)}/export?expertId=${data.expertId}`:API_ENDPOINTS.expertRevenue.periodExport(data.id);
 return <div className="space-y-xl"><Link className="inline-flex items-center gap-xs text-sm text-primary" to={admin?"/admin/revenue":"/lawyer/revenue"}><ArrowLeft className="h-4 w-4"/>Quay lại</Link><PageHeader title={`${data.expertNameSnapshot} · ${data.period.periodCode}`} subtitle="Statement giữ snapshot ticket, expert và hoa hồng tại thời điểm ghi nhận." actions={<div className="flex flex-wrap gap-sm"><Button variant="secondary" leftIcon={<Download className="h-4 w-4"/>} onClick={()=>void downloadRevenueExport(exportUrl,`doanh-thu-${data.period.periodCode}.xlsx`)}>Xuất XLSX</Button>{admin&&data.period.status!=="CLOSED"&&data.period.status!=="PAID"&&<Button variant="secondary" onClick={async()=>{const amount=prompt("Số tiền điều chỉnh (âm nếu giảm)");const reason=prompt("Lý do điều chỉnh");if(amount&&reason){await createRevenueAdjustment(data.period.id,data.expertId,undefined,Number(amount)>=0?"PAYOUT_CORRECTION":"REFUND",Number(amount),reason);await load();}}}>Thêm điều chỉnh</Button>}{admin&&["CONFIRMED","PARTIALLY_PAID"].includes(data.status)&&<Button onClick={async()=>{await markStatementPaymentPending(data.id);await load();}}>Chờ thanh toán</Button>}{admin&&data.status==="PAYMENT_PENDING"&&<Button onClick={async()=>{const ref=prompt("Mã tham chiếu thanh toán");if(ref){await markStatementPaid(data.id,ref);await load();}}}>Đánh dấu đã trả</Button>}</div>}/><div className="grid gap-md md:grid-cols-4"><Metric label="Phí tư vấn" value={data.grossConsultationFee}/><Metric label="Phí nền tảng" value={data.totalPlatformFee}/><Metric label="Điều chỉnh" value={data.adjustmentAmount}/><Metric label="Còn lại" value={data.remainingAmount}/></div><Card title="Thông tin đối soát"><div className="grid gap-sm text-sm md:grid-cols-3"><p>Trạng thái: <Badge>{data.status}</Badge></p><p>Đã trả: <b>{money(data.paidAmount)}</b></p><p>Tham chiếu: <b>{data.paymentReference||"-"}</b></p></div></Card><Card title="Ticket đã ghi nhận"><DataTable columns={items} data={data.items||[]} getRowKey={i=>i.id} emptyMessage="Không có ticket"/></Card><Card title="Điều chỉnh kỳ"><DataTable columns={adjustments} data={data.adjustments||[]} getRowKey={a=>a.id} emptyMessage="Không có điều chỉnh"/></Card></div>;}
function money(v:number){return formatVndCurrency(Number(v||0),"0 ₫","vi-VN");}function Metric({label,value}:{label:string;value:number}){return <Card className="p-md"><p className="text-xs uppercase text-on-surface-variant">{label}</p><p className="mt-xs text-xl font-bold">{money(value)}</p></Card>;}
