import type { AuditLog } from '../types/audit';
import type { BillingUsage, Invoice } from '../types/billing';
import type { LegalDocument } from '../types/document';
import type { KnowledgeArticle } from '../types/knowledgeBase';
import type { Project } from '../types/project';
import type { Report } from '../types/report';
import type { RiskDistribution, RiskFinding } from '../types/risk';
import type { ProcessingJob, SystemService } from '../types/system';
import type { WorkspaceUser } from '../types/user';

export const projects: Project[] = [
  {
    id: 'phoenix',
    name: 'M&A Acquisition: Project Phoenix',
    client: 'Acme Corp',
    description: 'Cross-border acquisition due diligence across services, IP, employment, and data processing agreements.',
    status: 'active',
    riskLevel: 'high',
    owner: 'Marcus Aurelius',
    jurisdiction: 'US / Vietnam / Singapore',
    documentCount: 84,
    highRiskCount: 14,
    updatedAt: 'Today, 10:42 AM',
    progress: 72,
    members: [
      { id: 'm1', name: 'Marcus Aurelius', role: 'Senior Counsel', initials: 'MA' },
      { id: 'm2', name: 'Nguyễn Hoàng', role: 'Legal Ops', initials: 'NH' },
      { id: 'm3', name: 'Jane Doe', role: 'Reviewer', initials: 'JD' },
    ],
    tags: ['M&A', 'Data Privacy', 'IP Rights'],
  },
  {
    id: 'merger-alpha-omega',
    name: 'Merger Alpha-Omega',
    client: 'Alpha Holdings',
    description: 'Strategic merger review with baseline commercial lease and vendor contract comparison.',
    status: 'processing',
    riskLevel: 'medium',
    owner: 'Jane Doe',
    jurisdiction: 'United Kingdom',
    documentCount: 47,
    highRiskCount: 6,
    updatedAt: 'Yesterday, 5:18 PM',
    progress: 58,
    members: [
      { id: 'm4', name: 'Jane Doe', role: 'Lead Counsel', initials: 'JD' },
      { id: 'm5', name: 'Trần Thu', role: 'Associate', initials: 'TT' },
    ],
    tags: ['Corporate', 'Lease', 'Vendor'],
  },
  {
    id: 'evergreen-real-estate',
    name: 'Evergreen Real Estate',
    client: 'Evergreen Partners',
    description: 'Lease portfolio normalization and clause deviation review.',
    status: 'active',
    riskLevel: 'low',
    owner: 'Richard S.',
    jurisdiction: 'California',
    documentCount: 33,
    highRiskCount: 1,
    updatedAt: 'Oct 24, 2024',
    progress: 88,
    members: [
      { id: 'm6', name: 'Richard S.', role: 'Real Estate Counsel', initials: 'RS' },
      { id: 'm7', name: 'Lê Văn', role: 'Viewer', initials: 'LV' },
    ],
    tags: ['Real Estate', 'Lease'],
  },
  {
    id: 'vendor-renewal-q2',
    name: 'Vendor Renewal Q2',
    client: 'TechFlow Inc.',
    description: 'Renewal cycle review across master service agreements and security addenda.',
    status: 'active',
    riskLevel: 'high',
    owner: 'Mary Smith',
    jurisdiction: 'US / EU',
    documentCount: 29,
    highRiskCount: 8,
    updatedAt: 'Oct 23, 2024',
    progress: 63,
    members: [
      { id: 'm8', name: 'Mary Smith', role: 'Commercial Counsel', initials: 'MS' },
      { id: 'm9', name: 'John Doe', role: 'Reviewer', initials: 'JD' },
    ],
    tags: ['Vendor', 'Renewal', 'Security'],
  },
  {
    id: 'compliance-audit-2023',
    name: '2023 Compliance Audit',
    client: 'Global Logistics',
    description: 'Historical compliance audit for privacy, employment, and anti-bribery representations.',
    status: 'finalized',
    riskLevel: 'medium',
    owner: 'Nguyễn Hoàng',
    jurisdiction: 'Vietnam',
    documentCount: 121,
    highRiskCount: 12,
    updatedAt: 'Oct 20, 2024',
    progress: 100,
    members: [
      { id: 'm10', name: 'Nguyễn Hoàng', role: 'Admin', initials: 'NH' },
      { id: 'm11', name: 'Trần Thu', role: 'Counsel', initials: 'TT' },
    ],
    tags: ['Compliance', 'Audit', 'Vietnam'],
  },
];

export const documents: LegalDocument[] = [
  {
    id: 'doc-msa-global-tech',
    name: 'MSA_Global_Tech_2024.pdf',
    type: 'Master Services Agreement',
    projectId: 'phoenix',
    projectName: 'M&A Acquisition: Project Phoenix',
    status: 'ready',
    riskLevel: 'high',
    owner: 'Marcus Aurelius',
    pages: 28,
    size: '1.4 MB',
    jurisdiction: 'United Kingdom',
    updatedAt: 'Today, 10:42 AM',
    summary: 'Aggressive indemnification, unilateral scope-change authority, and uncapped confidentiality liability require legal review.',
    clauses: [
      {
        ref: '2.2',
        title: 'Change Control',
        riskLevel: 'medium',
        text: 'The Provider may, at its sole discretion, modify the scope of services at any time with thirty days notice, provided such modifications do not materially degrade the overall service level.',
      },
      {
        ref: '3.1',
        title: 'Indemnification',
        riskLevel: 'high',
        text: 'Client shall indemnify and hold Provider harmless from all third-party claims, including claims caused by Provider negligence, without limitation as to amount.',
      },
      {
        ref: '8.4',
        title: 'Data Residency',
        riskLevel: 'medium',
        text: 'Data may be processed in any region selected by Provider where commercially reasonable security measures are in place.',
      },
    ],
  },
  {
    id: 'doc-service-agreement-v4',
    name: 'Service_Agreement_v4.pdf',
    type: 'Service Agreement',
    projectId: 'vendor-renewal-q2',
    projectName: 'Vendor Renewal Q2',
    status: 'processing',
    riskLevel: 'high',
    owner: 'Mary Smith',
    pages: 22,
    size: '900 KB',
    jurisdiction: 'Vietnam',
    updatedAt: 'Today, 9:18 AM',
    summary: 'Clause 4 includes a 200% indemnity multiplier and Clause 8 introduces uncapped confidentiality exposure.',
    clauses: [
      {
        ref: '4',
        title: 'Trách nhiệm bồi thường thiệt hại',
        riskLevel: 'high',
        text: 'Bên vi phạm phải bồi thường cho bên không vi phạm khoản tiền tương đương 200% tổng giá trị hợp đồng, bất kể thiệt hại thực tế có xảy ra hay không.',
      },
      {
        ref: '8',
        title: 'Bảo mật thông tin',
        riskLevel: 'medium',
        text: 'Bên vi phạm nghĩa vụ bảo mật phải chịu trách nhiệm vô hạn đối với mọi tổn thất của bên kia, bao gồm cả chi phí luật sư và chi phí gián tiếp.',
      },
    ],
  },
  {
    id: 'doc-nda-confidential',
    name: 'NDA_Confidential_Draft_v2.docx',
    type: 'Non-Disclosure Agreement',
    projectId: 'phoenix',
    projectName: 'M&A Acquisition: Project Phoenix',
    status: 'processing',
    riskLevel: 'medium',
    owner: 'Jane Doe',
    pages: 11,
    size: '450 KB',
    jurisdiction: 'Singapore',
    updatedAt: 'Today, 8:54 AM',
    summary: 'Mutuality language is mostly aligned. Residual knowledge and affiliate carve-outs require attention.',
    clauses: [
      {
        ref: '6.3',
        title: 'Residual Knowledge',
        riskLevel: 'medium',
        text: 'Receiving Party may use retained unaided memories for general business purposes so long as Confidential Information is not intentionally disclosed.',
      },
    ],
  },
  {
    id: 'doc-employment-nda',
    name: 'Employment_NDA_Review.pdf',
    type: 'Employment Agreement',
    projectId: 'compliance-audit-2023',
    projectName: '2023 Compliance Audit',
    status: 'ready',
    riskLevel: 'low',
    owner: 'Trần Thu',
    pages: 15,
    size: '730 KB',
    jurisdiction: 'Vietnam',
    updatedAt: 'Oct 24, 2024',
    summary: 'Standard confidentiality and IP assignment terms. No critical deviations from baseline.',
    clauses: [
      {
        ref: '5.1',
        title: 'Confidentiality',
        riskLevel: 'low',
        text: 'Employee shall preserve the confidentiality of non-public business information during and after employment.',
      },
    ],
  },
  {
    id: 'doc-lease-baseline',
    name: 'Acquisition_Target_Lease.pdf',
    type: 'Commercial Lease',
    projectId: 'merger-alpha-omega',
    projectName: 'Merger Alpha-Omega',
    status: 'pending',
    riskLevel: 'medium',
    owner: 'Richard S.',
    pages: 41,
    size: '2.8 MB',
    jurisdiction: 'United Kingdom',
    updatedAt: 'Oct 21, 2024',
    summary: 'Assignment and change-of-control provisions may affect transaction closing conditions.',
    clauses: [
      {
        ref: '14.2',
        title: 'Assignment',
        riskLevel: 'medium',
        text: 'Tenant shall not assign this Lease by operation of law or otherwise without prior written consent of Landlord.',
      },
    ],
  },
];

export const riskFindings: RiskFinding[] = [
  {
    id: 'risk-001',
    title: 'Rủi ro bồi thường 200%',
    level: 'critical',
    clauseRef: 'Điều 4',
    summary: 'Điều khoản bồi thường mang tính chất phạt quá mức theo Bộ luật Dân sự và Luật Thương mại Việt Nam.',
    plainLanguage:
      'Pháp luật Việt Nam thường giới hạn mức phạt vi phạm không quá 8% giá trị phần nghĩa vụ bị vi phạm trong thương mại. Con số 200% là phi thực tế và có khả năng bị tòa án bác bỏ.',
    legalBasis:
      'Áp dụng Điều 301 Luật Thương mại 2005 và Điều 418 Bộ luật Dân sự 2015. Mức phạt tổng cộng không được vượt quá giới hạn luật định trừ trường hợp đặc thù.',
    citation: 'Điều 301 Luật Thương mại 2005',
    suggestedAction: 'Thay bằng trần bồi thường 8% phần nghĩa vụ vi phạm hoặc bồi thường thiệt hại thực tế có chứng minh.',
  },
  {
    id: 'risk-002',
    title: 'Trách nhiệm vô hạn',
    level: 'medium',
    clauseRef: 'Điều 8',
    summary: 'Điều khoản bảo mật yêu cầu trách nhiệm vô hạn cho mọi loại thiệt hại, bao gồm chi phí gián tiếp.',
    plainLanguage: 'Trách nhiệm vô hạn tạo phơi nhiễm tài chính không dự báo được và có thể vượt phạm vi bảo hiểm hiện có.',
    legalBasis: 'Các bên có thể thỏa thuận giới hạn trách nhiệm phù hợp với tính chất nghĩa vụ và mức độ thiệt hại thực tế.',
    citation: 'Bộ luật Dân sự 2015, nguyên tắc bồi thường thiệt hại',
    suggestedAction: 'Giới hạn trách nhiệm ở mức 12 tháng phí dịch vụ, trừ hành vi cố ý hoặc vi phạm dữ liệu nghiêm trọng.',
  },
  {
    id: 'risk-003',
    title: 'Data residency ambiguity',
    level: 'low',
    clauseRef: 'Sec. 22',
    summary: 'Processing location language lacks a notification obligation for cross-border transfers.',
    plainLanguage: 'The clause is broadly acceptable but should require advance notice for regulated personal data transfers.',
    legalBasis: 'Data protection regimes often require transparency and transfer-impact safeguards for cross-border processing.',
    citation: 'GDPR Articles 44-49; Decree 13/2023/ND-CP',
    suggestedAction: 'Add notice and subprocessors list-update obligations.',
  },
];

export const reports: Report[] = [
  {
    id: 'lg-2024-0812-x',
    title: 'TechFlow MSA Executive Summary',
    template: 'Executive Summary',
    documentName: 'Master Service Agreement - TechFlow Inc.',
    author: 'John Doe',
    status: 'ready',
    riskLevel: 'high',
    createdAt: 'Oct 24, 2024',
    summary: 'Moderate-high risk profile driven by aggressive indemnification and vague termination triggers.',
  },
  {
    id: 'lg-2024-0813-a',
    title: 'Full Risk Review - Artemis NDA',
    template: 'Full Risk Review',
    documentName: 'NDA - Project Artemis',
    author: 'LexiGuard AI',
    status: 'processing',
    riskLevel: 'medium',
    createdAt: 'Oct 25, 2024',
    summary: 'AI processing at 74%. Residual knowledge and affiliate sharing sections are under review.',
  },
  {
    id: 'lg-2024-0802-c',
    title: 'Compliance Audit - Global Logistics',
    template: 'Compliance Audit',
    documentName: 'Global Logistics Contract Bundle',
    author: 'Mary Smith',
    status: 'ready',
    riskLevel: 'low',
    createdAt: 'Oct 21, 2024',
    summary: 'No critical compliance blockers detected. Privacy annex requires metadata correction.',
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: 'REQ-992-AC82',
    timestamp: 'Today, 10:42 AM',
    user: 'Jane Doe',
    initials: 'JD',
    action: 'AI Risk Review',
    documentRef: 'ND-2024-081',
    latency: '1.2s',
    status: 'success',
    ipAddress: '192.168.1.14',
    tokens: 4210,
    model: 'lexi-guard-v4-pro',
  },
  {
    id: 'REQ-992-AC79',
    timestamp: 'Today, 10:38 AM',
    user: 'Richard S.',
    initials: 'RS',
    action: 'Version Comparison',
    documentRef: 'L-AGREE-V2',
    latency: '2.8s',
    status: 'success',
    ipAddress: '192.168.1.18',
    tokens: 7988,
    model: 'lexi-guard-v4-pro',
  },
  {
    id: 'REQ-992-AC54',
    timestamp: 'Today, 10:15 AM',
    user: 'Jane Doe',
    initials: 'JD',
    action: 'Legal Chat Query',
    documentRef: 'N/A',
    latency: '0.9s',
    status: 'rateLimited',
    ipAddress: '192.168.1.14',
    tokens: 1800,
    model: 'lexi-guard-v4-chat',
  },
  {
    id: 'REQ-992-AC41',
    timestamp: 'Today, 09:52 AM',
    user: 'System Agent',
    initials: 'AI',
    action: 'Database Sync',
    documentRef: 'System',
    latency: '14.2s',
    status: 'pending',
    ipAddress: '127.0.0.1',
    tokens: 0,
    model: 'indexer-v2',
  },
];

export const workspaceUsers: WorkspaceUser[] = [
  {
    id: 'u1',
    name: 'Nguyễn Hoàng',
    email: 'hoang.nguyen@lexiguard.ai',
    role: 'Quản trị viên',
    status: 'active',
    lastAccess: '2 giờ trước',
    initials: 'NH',
  },
  {
    id: 'u2',
    name: 'Trần Thu',
    email: 'thu.tran@lexiguard.ai',
    role: 'Luật sư',
    status: 'active',
    lastAccess: '1 ngày trước',
    initials: 'TT',
  },
  {
    id: 'u3',
    name: 'Lê Văn',
    email: 'van.le@lexiguard.ai',
    role: 'Người xem',
    status: 'offline',
    lastAccess: '3 ngày trước',
    initials: 'LV',
  },
];

export const knowledgeArticles: KnowledgeArticle[] = [
  {
    id: 'decree-13-2023',
    title: 'Decree No. 13/2023/ND-CP on Personal Data Protection',
    category: 'Decrees',
    jurisdiction: 'Vietnam',
    status: 'ready',
    updatedAt: 'Aug 12, 2024',
    chunks: 1284,
    impactedContracts: 24,
    summary: 'Primary Vietnamese personal data protection source used in privacy annex and cross-border transfer analysis.',
  },
  {
    id: 'lta-2005-article-301',
    title: 'Article 301, Law on Commerce 2005',
    category: 'Statutes',
    jurisdiction: 'Vietnam',
    status: 'ready',
    updatedAt: 'Jul 2, 2024',
    chunks: 142,
    impactedContracts: 61,
    summary: 'Statutory basis for penalty limitation analysis in commercial agreements.',
  },
  {
    id: 'uk-modern-slavery-act',
    title: 'UK Modern Slavery Act Supply Chain Guidance',
    category: 'Guidance',
    jurisdiction: 'United Kingdom',
    status: 'ready',
    updatedAt: 'Jun 18, 2024',
    chunks: 411,
    impactedContracts: 9,
    summary: 'Guidance for supplier code of conduct and reporting obligations.',
  },
  {
    id: 'corporate-msa-baseline',
    title: 'Corporate MSA Baseline Clause Playbook',
    category: 'Internal Policy',
    jurisdiction: 'Global',
    status: 'draft',
    updatedAt: 'Oct 20, 2024',
    chunks: 360,
    impactedContracts: 73,
    summary: 'Approved fallback positions for liability, indemnity, confidentiality, and termination clauses.',
  },
];

export const systemServices: SystemService[] = [
  {
    id: 'ollama',
    name: 'Ollama Instance',
    status: 'online',
    value: 'V 0.1.28',
    detail: 'Local host: 127.0.0.1:11434',
  },
  {
    id: 'llama',
    name: 'Llama-3-Legal-8B',
    status: 'active',
    value: '94.2% Load',
    detail: 'Quantized: Q4_K_M',
    metric: 94.2,
  },
  {
    id: 'pinecone',
    name: 'Pinecone Vector DB',
    status: 'ready',
    value: '12.4M Vectors',
    detail: 'Region: us-east-1-aws',
  },
  {
    id: 'storage',
    name: 'Secure Storage',
    status: 'ready',
    value: '2.4 TB / 4 TB',
    detail: 'Encrypted AES-256',
    metric: 60,
  },
];

export const processingJobs: ProcessingJob[] = [
  {
    id: '#JOB-8841',
    resource: 'Document_0984_Contract.pdf',
    description: 'Scanning for risk clauses...',
    status: 'processing',
    progress: 84,
  },
  {
    id: '#JOB-8832',
    resource: 'Audit_Log_2023_Final.docx',
    description: 'Pending LLM Analysis',
    status: 'pending',
    progress: 0,
  },
  {
    id: '#JOB-8829',
    resource: 'NDA_LexiGuard_Internal.pdf',
    description: 'Scheduled Task',
    status: 'pending',
    progress: 0,
  },
  {
    id: '#JOB-8821',
    resource: 'Vector_Emb_Proc',
    description: 'Embedding worker timeout',
    status: 'failed',
    progress: 0,
    errorType: 'TIMEOUT',
    timestamp: '10:24 AM',
  },
  {
    id: '#JOB-8710',
    resource: 'Legal_LLM_Infr',
    description: 'Out of memory during inference',
    status: 'failed',
    progress: 0,
    errorType: 'OOM_ERR',
    timestamp: '09:12 AM',
  },
  {
    id: '#JOB-8655',
    resource: 'OCR_Parse_Sv',
    description: 'Corrupt PDF parse failure',
    status: 'failed',
    progress: 0,
    errorType: 'CORRUPT_PDF',
    timestamp: '08:45 AM',
  },
];

export const billingUsage: BillingUsage[] = [
  { id: 'ai-requests', label: 'AI Requests', used: 1284, limit: 5000, unit: 'requests' },
  { id: 'tokens', label: 'Token Usage', used: 842000, limit: 2000000, unit: 'tokens' },
  { id: 'storage', label: 'Secure Storage', used: 2.4, limit: 4, unit: 'TB' },
  { id: 'users', label: 'Seats', used: 24, limit: 50, unit: 'users' },
];

export const invoices: Invoice[] = [
  { id: 'INV-2024-101', date: 'Oct 1, 2024', amount: 4200, status: 'ready' },
  { id: 'INV-2024-091', date: 'Sep 1, 2024', amount: 4200, status: 'ready' },
  { id: 'INV-2024-081', date: 'Aug 1, 2024', amount: 3900, status: 'ready' },
];

export const riskDistribution: RiskDistribution = {
  critical: 12,
  high: 31,
  medium: 44,
  low: 86,
};

export const comparisonRows = [
  {
    id: 'cmp-001',
    name: 'Service_Master_v4_Final',
    original: 'MSA_Standard_2023.pdf',
    revised: 'MSA_Redline_Client_A.docx',
    project: 'Global SLAs',
    highRisks: 3,
    date: 'Oct 24, 2024',
  },
  {
    id: 'cmp-002',
    name: 'Employment_NDA_Review',
    original: 'NDA_Template_v2.pdf',
    revised: 'Jane_Doe_Contract_Signed.pdf',
    project: 'HR Compliance',
    highRisks: 0,
    date: 'Oct 22, 2024',
  },
  {
    id: 'cmp-003',
    name: 'Tech_Vendor_Agreement_Delta',
    original: 'Vendor_Master_v1.docx',
    revised: 'Vendor_Delta_Comments.docx',
    project: 'IT Procurement',
    highRisks: 1,
    date: 'Oct 19, 2024',
  },
  {
    id: 'cmp-004',
    name: 'M&A_Due_Diligence_A-1',
    original: 'Acquisition_Target_Lease.pdf',
    revised: 'Baseline_Commercial_Lease.pdf',
    project: 'Acme M&A',
    highRisks: 12,
    date: 'Oct 15, 2024',
  },
];

export const dashboardTrend = [42, 51, 38, 62, 48, 76, 89];
