export type Status =
  | 'ready'
  | 'processing'
  | 'pending'
  | 'success'
  | 'failed'
  | 'active'
  | 'deleted'
  | 'offline'
  | 'online'
  | 'draft'
  | 'finalized'
  | 'archived'
  | 'rateLimited'
  | 'ACTIVE'
  | 'DELETED';