-- Complete PostgreSQL baseline generated from the current Hibernate entity metadata.
-- It intentionally contains only additive CREATE statements so existing data is preserved.
-- Foreign-key reconciliation is handled separately to avoid duplicating constraints on legacy databases.

CREATE TABLE IF NOT EXISTS ai_citations (id varchar(255) not null, chunk_index integer, created_at timestamp(6) not null, excerpt TEXT, label varchar(255) not null, page_number integer, score float(53), source_reference_id varchar(255) not null, source_type varchar(255) not null check ((source_type in ('DOCUMENT','KNOWLEDGE_BASE','CONTRACT','CHAT_MESSAGE','LEGAL_TICKET'))), uri varchar(255), chat_message_id varchar(255), legal_ticket_id varchar(255), primary key (id));

CREATE TABLE IF NOT EXISTS ai_reports (id varchar(255) not null, created_at timestamp(6) not null, details_json TEXT, report_type varchar(255) not null, source_reference_id varchar(255) not null, source_type varchar(255) not null, status varchar(255) not null check ((status in ('OPEN','UNDER_REVIEW','RESOLVED','REJECTED'))), summary TEXT not null, updated_at timestamp(6) not null, submitted_by_id bigint, workspace_id varchar(255), primary key (id));

CREATE TABLE IF NOT EXISTS chat_message_feedbacks (id varchar(255) not null, comment TEXT, created_at timestamp(6) not null, feedback_type varchar(255) not null check ((feedback_type in ('LIKE','DISLIKE'))), rating varchar(255) not null check ((rating in ('THUMBS_UP','THUMBS_DOWN'))), reason TEXT, reasons TEXT, updated_at timestamp(6) not null, chat_message_id varchar(255) not null, chat_session_id varchar(255) not null, user_id bigint not null, primary key (id), constraint uk_chat_message_feedback_message_user unique (chat_message_id, user_id));

CREATE TABLE IF NOT EXISTS chat_messages (id varchar(255) not null, ai_model varchar(255), citation_metadata_json TEXT, completion_tokens integer, confidence_score float(53), content TEXT not null, context_snapshot_json TEXT, created_at timestamp(6) not null, error_message TEXT, legal_domain varchar(255), message_type varchar(255) not null check ((message_type in ('NORMAL_CHAT','DOCUMENT_ANALYSIS','SYSTEM_NOTICE'))), missing_information TEXT, prompt_tokens integer, request_id varchar(255), resolved_mode varchar(255) check ((resolved_mode in ('AUTO','LEGAL_QA','DOCUMENT_ANALYSIS'))), risk_level varchar(255) check ((risk_level in ('NONE','LOW','MEDIUM','HIGH','CRITICAL','UNKNOWN'))), role varchar(255) not null check ((role in ('USER','ASSISTANT','SYSTEM'))), should_suggest_ticket boolean, status varchar(255) not null check ((status in ('SENT','PROCESSING','COMPLETED','FAILED'))), suggestion_reason TEXT, suggestion_type varchar(255) check ((suggestion_type in ('DIRECT_ANSWER','ASK_UPLOAD_CONTRACT','ASK_CONTRACT_TYPE','ASK_USER_ROLE','ASK_TARGET_CLAUSE','ASK_MORE_FACTS','SUGGEST_REVISE_CLAUSE','SUGGEST_NEGOTIATION','REDIRECT_TO_SUPPORTED_SCOPE','REFUSE_AND_REDIRECT','NONE','ASK_MORE_INFO','SUGGEST_LAWYER','REQUIRE_LAWYER'))), total_tokens integer, updated_at timestamp(6) not null, user_action_hint varchar(255) check ((user_action_hint in ('CONTINUE_CHAT','PROVIDE_MORE_INFO','CREATE_TICKET','UPLOAD_CONTRACT','CONTACT_LAWYER'))), chat_session_id varchar(255) not null, user_id bigint not null, primary key (id));

CREATE TABLE IF NOT EXISTS chat_session_documents (id varchar(255) not null, active boolean not null, attached_at timestamp(6) not null, updated_at timestamp(6) not null, chat_session_id varchar(255) not null, document_id varchar(255) not null, user_id bigint not null, primary key (id), constraint uk_chat_session_document unique (chat_session_id, document_id));

CREATE TABLE IF NOT EXISTS chat_sessions (id varchar(255) not null, active_document_ids_json TEXT, context_json TEXT, context_version bigint, conversation_mode varchar(255), conversation_summary_json TEXT, conversation_user_role varchar(255), created_at timestamp(6) not null, focused_document_id varchar(255), is_default boolean not null, is_shared boolean not null, last_message_at timestamp(6), memory_json TEXT, memory_updated_at timestamp(6), message_attached_document_ids_json TEXT, share_token varchar(255) unique, shared_at timestamp(6), status varchar(255) not null check ((status in ('ACTIVE','DELETED'))), summary TEXT, summary_through_message_id varchar(255), summary_updated_at timestamp(6), title varchar(255) not null, updated_at timestamp(6) not null, user_id bigint not null, workspace_id varchar(255) not null, primary key (id));

CREATE TABLE IF NOT EXISTS contract_generation_jobs (id varchar(255) not null, created_at timestamp(6) not null, error_message TEXT, input_json TEXT not null, output_draft TEXT, prompt_snapshot TEXT, request_id varchar(255) not null unique, status varchar(255) not null check ((status in ('QUEUED','PROCESSING','COMPLETED','FAILED'))), updated_at timestamp(6) not null, requester_id bigint not null, source_document_id varchar(255), template_id bigint, workspace_id varchar(255) not null, primary key (id));

CREATE TABLE IF NOT EXISTS contract_templates (id bigint generated by default as identity, category varchar(255) not null, content TEXT not null, created_at timestamp(6) not null, description TEXT, jurisdiction varchar(255), name varchar(255) not null, status varchar(255) not null check ((status in ('ACTIVE','INACTIVE','ARCHIVED'))), template_code varchar(255) not null unique, updated_at timestamp(6) not null, version integer not null, primary key (id));

CREATE TABLE IF NOT EXISTS contract_versions (id varchar(255) not null, change_summary TEXT, content TEXT not null, created_at timestamp(6) not null, generated_by_ai boolean not null, version_no integer not null, contract_id varchar(255) not null, generated_by_id bigint, generation_job_id varchar(255), primary key (id), constraint uk_contract_version_no unique (contract_id, version_no));

CREATE TABLE IF NOT EXISTS conversation_shares (id varchar(255) not null, access_mode varchar(255) not null check ((access_mode in ('PARTICIPANTS_ONLY'))), created_at timestamp(6) not null, expires_at timestamp(6) not null, revoked_at timestamp(6), session_id varchar(255) not null, share_scope varchar(255) not null check ((share_scope in ('SELECTED_RESPONSE','RELATED_MESSAGES','FULL_CONVERSATION','TICKET_CONTEXT_ONLY'))), share_token_hash varchar(64) not null unique, created_by_id bigint not null, ticket_id varchar(255) not null, primary key (id));

CREATE TABLE IF NOT EXISTS customer_plans (id bigint generated by default as identity, auto_renew boolean not null, billing_cycle_end_at timestamp(6), billing_cycle_start_at timestamp(6), cancel_reason TEXT, created_at timestamp(6) not null, end_date timestamp(6), plan_change_effective_at timestamp(6), start_date timestamp(6), status varchar(255) not null check ((status in ('PENDING','ACTIVE','EXPIRED','CANCELLED'))), updated_at timestamp(6) not null, usage_end_at timestamp(6), usage_start_at timestamp(6), used_quota integer not null, customer_id bigint not null, scheduled_subscription_plan_id bigint, subscription_plan_id bigint not null, primary key (id));

CREATE TABLE IF NOT EXISTS documents (id varchar(255) not null, chunk_count integer, contract_type varchar(255) check ((contract_type in ('RENTAL','PART_TIME_EMPLOYMENT','INTERNSHIP','COLLABORATOR','FREELANCE_SERVICE','SMALL_ASSET_SALE','PERSONAL_LOAN','UNSUPPORTED','UNKNOWN'))), contract_type_confirmed boolean not null, document_purpose varchar(255) check ((document_purpose in ('USER_FILE','LAWYER_ATTACHMENT','ADMIN_ATTACHMENT','CONTRACT_ATTACHMENT','KNOWLEDGE_SOURCE'))), error_message TEXT, file_path varchar(255) not null, file_size bigint, file_type varchar(255), original_file_name varchar(255) not null, processed_at timestamp(6), source_type varchar(255) not null, status varchar(255) not null, stored_file_name varchar(255) not null, updated_at timestamp(6), uploaded_at timestamp(6), visibility_scope varchar(255) check ((visibility_scope in ('CUSTOMER','LAWYER','ADMIN','ALL_INTERNAL'))), legal_ticket_id varchar(255), user_id bigint not null, workspace_id varchar(255) not null, primary key (id));

CREATE TABLE IF NOT EXISTS feedback_survey_responses (id varchar(255) not null, answer_json TEXT, comment TEXT, created_at timestamp(6) not null, rating integer, source_reference_id varchar(255), respondent_id bigint, survey_id varchar(255) not null, primary key (id));

CREATE TABLE IF NOT EXISTS feedback_surveys (id varchar(255) not null, code varchar(255) not null unique, created_at timestamp(6) not null, description TEXT, status varchar(255) not null check ((status in ('DRAFT','ACTIVE','CLOSED','ARCHIVED'))), survey_type varchar(255) not null check ((survey_type in ('SATISFACTION','PRODUCT','BUG','USABILITY'))), target_type varchar(255) not null, title varchar(255) not null, updated_at timestamp(6) not null, created_by_id bigint not null, workspace_id varchar(255), primary key (id));

CREATE TABLE IF NOT EXISTS knowledge_base_entries (id varchar(255) not null, active boolean not null, category varchar(255) not null, code varchar(255) not null unique, created_at timestamp(6) not null, current_status varchar(255) not null check ((current_status in ('PENDING','UPLOADED','PROCESSING','INGESTED','REVIEWING','PUBLIC','ARCHIVED','FAILED'))), current_version_no integer not null, scope varchar(255) not null check ((scope in ('GLOBAL','WORKSPACE'))), title varchar(255) not null, updated_at timestamp(6) not null, created_by_id bigint not null, workspace_id varchar(255), primary key (id));

CREATE TABLE IF NOT EXISTS knowledge_base_versions (id varchar(255) not null, active boolean, archived_at timestamp(6), chunk_count integer, created_at timestamp(6) not null, description TEXT, effective_date varchar(255), ingest_error_message TEXT, extracted_content TEXT not null, failed_reason TEXT, ingest_notified_at timestamp(6), ingest_source varchar(100), ingest_status varchar(255) check ((ingest_status in ('PENDING','UPLOADED','PROCESSING','INGESTED','REVIEWING','PUBLIC','ARCHIVED','FAILED'))), ingested_at timestamp(6), neo4j_document_id varchar(255), original_file_name varchar(255), published_at timestamp(6), raw_content TEXT, review_decision varchar(255) check ((review_decision in ('APPROVE','REQUEST_CHANGES','REJECT'))), reviewed_at timestamp(6), source_content_type varchar(255), source_file_hash varchar(64), source_file_size bigint, source_relative_path TEXT, source_storage_path TEXT, source_uploaded_at timestamp(6), source_version_label varchar(255), status varchar(255) not null check ((status in ('PENDING','UPLOADED','PROCESSING','INGESTED','REVIEWING','PUBLIC','ARCHIVED','FAILED'))), updated_at timestamp(6) not null, version_no integer not null, visibility varchar(255) check ((visibility in ('PRIVATE','PUBLIC'))), archived_by_id bigint, ingested_by_id bigint, knowledge_base_entry_id varchar(255) not null, published_by_id bigint, reviewed_by_id bigint, source_document_id varchar(255), primary key (id), constraint uk_knowledge_base_version_no unique (knowledge_base_entry_id, version_no));

CREATE TABLE IF NOT EXISTS knowledge_ingestion_jobs (id varchar(255) not null, completed_at timestamp(6), created_at timestamp(6) not null, error_message TEXT, job_payload TEXT, progress_percent integer, request_id varchar(255) not null unique, started_at timestamp(6), status varchar(255) not null check ((status in ('PENDING','UPLOADED','PROCESSING','INGESTED','REVIEWING','PUBLIC','ARCHIVED','FAILED'))), ingested_by_id bigint, knowledge_base_version_id varchar(255) not null, primary key (id));

CREATE TABLE IF NOT EXISTS legal_ticket_messages (id varchar(255) not null, content TEXT not null, created_at timestamp(6) not null, deleted_at timestamp(6), edited_at timestamp(6), internal_only boolean not null, message_type varchar(255) not null check ((message_type in ('CUSTOMER_REPLY','EXPERT_REQUEST_MORE_INFO','EXPERT_RESPONSE','ADMIN_NOTE','SYSTEM'))), sender_role varchar(255), reply_to_message_id varchar(255), sender_id bigint not null, ticket_id varchar(255) not null, primary key (id));

CREATE TABLE IF NOT EXISTS legal_tickets (id varchar(255) not null, admin_note TEXT, ai_evidence TEXT, answer TEXT, assigned_at timestamp(6), cancelled_at timestamp(6), clause_reference varchar(255), close_reason TEXT, closed_at timestamp(6), confidence_score float(53), conversation_scope varchar(255) check ((conversation_scope in ('SELECTED_RESPONSE','RELATED_MESSAGES','FULL_CONVERSATION','TICKET_CONTEXT_ONLY'))), created_at timestamp(6) not null, customer_note TEXT, deleted boolean not null, deleted_at timestamp(6), description TEXT, expert_answer TEXT, expert_internal_note TEXT, focused_document_id varchar(255), issue_fingerprint varchar(255), issue_summary TEXT, issue_title varchar(255), last_customer_message_at timestamp(6), last_lawyer_message_at timestamp(6), legal_domain varchar(255), missing_information TEXT, page_number integer, priority varchar(255) check ((priority in ('LOW','NORMAL','HIGH','URGENT'))), problematic_clause TEXT, question TEXT not null, recipient_type varchar(255) check ((recipient_type in ('EXPERT','ADMIN'))), recommended_action TEXT, rejection_reason TEXT, related_chat_message_id varchar(255), related_chat_session_id varchar(255), reopened_at timestamp(6), request_id varchar(255) not null, resolved_at timestamp(6), risk_level varchar(255) check ((risk_level in ('NONE','LOW','MEDIUM','HIGH','CRITICAL','UNKNOWN'))), shared_document_ids_json TEXT, should_suggest_ticket boolean, source_assistant_message_id varchar(255), source_user_message_id varchar(255), status varchar(255) not null check ((status in ('OPEN','ASSIGNED','WAITING_FOR_USER','WAITING_FOR_EXPERT','DRAFT','PENDING_ADMIN_REVIEW','REJECTED_BY_ADMIN','ASSIGNED_TO_LAWYER','IN_REVIEW','NEED_MORE_INFO','CUSTOMER_RESPONDED','RESOLVED','CLOSED','CANCELLED','REOPENED'))), suggestion_reason TEXT, suggestion_type varchar(255) check ((suggestion_type in ('DIRECT_ANSWER','ASK_UPLOAD_CONTRACT','ASK_CONTRACT_TYPE','ASK_USER_ROLE','ASK_TARGET_CLAUSE','ASK_MORE_FACTS','SUGGEST_REVISE_CLAUSE','SUGGEST_NEGOTIATION','REDIRECT_TO_SUPPORTED_SCOPE','REFUSE_AND_REDIRECT','NONE','ASK_MORE_INFO','SUGGEST_LAWYER','REQUIRE_LAWYER'))), ticket_code varchar(255) unique, ticket_type varchar(255) check ((ticket_type in ('SYSTEM_ERROR','QUERY_ERROR','CONTACT_EXPERT','REFUND_REQUEST'))), title varchar(255), updated_at timestamp(6) not null, user_action_hint varchar(255) check ((user_action_hint in ('CONTINUE_CHAT','PROVIDE_MORE_INFO','CREATE_TICKET','UPLOAD_CONTRACT','CONTACT_LAWYER'))), version bigint, assigned_lawyer_id bigint, created_by_id bigint not null, document_id varchar(255), workspace_id varchar(255), primary key (id), constraint uk_legal_ticket_request_creator unique (request_id, created_by_id));

CREATE TABLE IF NOT EXISTS payment_transactions (id bigint generated by default as identity, amount numeric(38,2) not null, created_at timestamp(6) not null, gateway_response_code varchar(255), gateway_transaction_no varchar(255), paid_at timestamp(6), payment_method varchar(255) not null check ((payment_method in ('CASH','BANK_TRANSFER','MOMO','VNPAY','CREDIT_CARD'))), payment_status varchar(255) not null check ((payment_status in ('PENDING','SUCCESS','FAILED','CANCELLED','REFUNDED'))), payment_url varchar(2048), transaction_code varchar(255) not null unique, updated_at timestamp(6) not null, customer_id bigint not null, customer_plan_id bigint, subscription_plan_id bigint not null, primary key (id));

CREATE TABLE IF NOT EXISTS refresh_tokens (id bigint generated by default as identity, expiry_date timestamp(6) with time zone not null, revoked boolean not null, token varchar(255) not null unique, user_id bigint not null, primary key (id));

CREATE TABLE IF NOT EXISTS refund_requests (id bigint generated by default as identity, account_holder_name varchar(255), account_number varchar(255), admin_note TEXT, amount numeric(38,2) not null, bank_name varchar(255), confirmation_expires_at timestamp(6), confirmation_token_hash varchar(64), confirmation_used_token_hash varchar(64), created_at timestamp(6) not null, email_confirmed_at timestamp(6), invoice_id varchar(255), reason TEXT not null, status varchar(255) not null check ((status in ('NEW','ADMIN_REVIEWING','WAITING_USER_BANK_INFO','WAITING_EMAIL_CONFIRMATION','EMAIL_CONFIRMED','REFUND_REQUEST_CREATED','REFUNDED','CLOSED','REQUESTED','APPROVED','REJECTED','PROCESSING','COMPLETED'))), updated_at timestamp(6) not null, customer_plan_id bigint, legal_ticket_id varchar(255) unique, payment_transaction_id bigint not null, requested_by_id bigint not null, primary key (id));

CREATE TABLE IF NOT EXISTS revenue_settings (id bigint not null, commission_rate numeric(5,4) not null, updated_at timestamp(6), updated_by bigint, primary key (id));

CREATE TABLE IF NOT EXISTS roles (id bigint generated by default as identity, name varchar(255) not null unique check ((name in ('CUSTOMER','EXPERT','ADMIN'))), primary key (id));

CREATE TABLE IF NOT EXISTS subscription_plans (id bigint generated by default as identity, active boolean not null, ai_quota integer, allow_contact_expert_ticket boolean, allow_query_error_ticket boolean, allow_system_error_ticket boolean, created_at timestamp(6) not null, description TEXT, duration_days integer not null, feature_limits_json TEXT, max_attached_documents_per_session integer, max_contracts_per_workspace integer, max_draft_contracts integer, max_file_size_mb integer, max_quota integer not null, max_workspaces integer, plan_name varchar(255) not null, plan_type varchar(255) not null, price numeric(38,2) not null, storage_limit_mb integer, ticket_quota integer, tier varchar(255) check ((tier in ('BASIC','PRO','PREMIUM'))), updated_at timestamp(6) not null, primary key (id));

CREATE TABLE IF NOT EXISTS subscription_usage (id bigint generated by default as identity, consumed_units integer not null, created_at timestamp(6) not null, metadata_json TEXT, reference_id varchar(255), usage_type varchar(255) not null check ((usage_type in ('AI_QUERY','CONTRACT_GENERATION','TICKET_CREATE','KNOWLEDGE_SEARCH','CHAT_MESSAGE'))), customer_plan_id bigint not null, primary key (id));

CREATE TABLE IF NOT EXISTS system_notifications (id bigint generated by default as identity, created_at timestamp(6) not null, dedup_key varchar(255) not null, entity_id varchar(255) not null, entity_type varchar(255) not null, message TEXT not null, is_read boolean not null, title varchar(255) not null, type varchar(255) not null, recipient_user_id bigint not null, primary key (id), constraint uk_system_notification_dedup unique (dedup_key));

CREATE TABLE IF NOT EXISTS ticket_attachments (id varchar(255) not null, checksum varchar(64) not null, created_at timestamp(6) not null, deleted_at timestamp(6), mime_type varchar(255) not null, original_file_name varchar(255) not null, owner_id varchar(255) not null, owner_type varchar(255) not null check ((owner_type in ('TICKET_DRAFT','TICKET','TICKET_MESSAGE'))), scan_status varchar(255) not null check ((scan_status in ('NOT_CONFIGURED','PENDING','CLEAN','REJECTED'))), size_bytes bigint not null, storage_key varchar(255) not null unique, stored_file_name varchar(255) not null, ticket_id varchar(255), upload_status varchar(255) not null check ((upload_status in ('UPLOADED','FAILED','REMOVED'))), uploaded_by_id bigint not null, primary key (id));

CREATE TABLE IF NOT EXISTS ticket_audit_logs (id varchar(255) not null, action varchar(255) not null, created_at timestamp(6) not null, metadata_json TEXT, ticket_id varchar(255) not null, actor_id bigint not null, primary key (id));

CREATE TABLE IF NOT EXISTS ticket_context_snapshots (id varchar(255) not null, assistant_answer TEXT, citation_snapshot_json TEXT, content_hash varchar(64) not null, conversation_title varchar(255), created_at timestamp(6) not null, document_snapshot_json TEXT, selected_message_snapshot_json TEXT, user_question TEXT not null, ticket_id varchar(255) not null unique, primary key (id));

CREATE TABLE IF NOT EXISTS user_contracts (id varchar(255) not null, contract_type varchar(255) not null, created_at timestamp(6) not null, current_content_hash varchar(255), current_version_no integer not null, last_generated_at timestamp(6), status varchar(255) not null check ((status in ('DRAFT','GENERATED','ACTIVE','ARCHIVED'))), title varchar(255) not null, updated_at timestamp(6) not null, generation_job_id varchar(255), owner_id bigint not null, source_document_id varchar(255), template_id bigint, workspace_id varchar(255) not null, primary key (id));

CREATE TABLE IF NOT EXISTS users (id bigint generated by default as identity, accepted_terms boolean not null, active boolean not null, description TEXT, email varchar(255) not null unique, email_delivery_status varchar(16), email_verification_last_used_token varchar(255), email_verification_requested_at timestamp(6), email_verification_token varchar(255), email_verification_token_expiry timestamp(6), email_verification_token_used_at timestamp(6), email_verified boolean not null, email_verified_at timestamp(6), first_name varchar(255) not null, last_name varchar(255) not null, legal_domain varchar(255), must_change_password boolean not null, password varchar(255) not null, password_reset_deadline timestamp(6), specialty varchar(255), role_id bigint not null, primary key (id));

CREATE TABLE IF NOT EXISTS workspaces (id varchar(255) not null, created_at timestamp(6), description TEXT, name varchar(255) not null, status varchar(255) not null, updated_at timestamp(6), user_id bigint not null, primary key (id));

CREATE INDEX IF NOT EXISTS idx_chat_messages_session_status_created on chat_messages (chat_session_id, status, created_at);

CREATE INDEX IF NOT EXISTS idx_ticket_attachments_owner on ticket_attachments (owner_type, owner_id);

CREATE INDEX IF NOT EXISTS idx_ticket_audit_ticket_created on ticket_audit_logs (ticket_id, created_at);

