-- Reconcile columns introduced by incremental feature migrations with the
-- current JPA metadata. All changes are additive or widening conversions.

ALTER TABLE chat_sessions
    ADD COLUMN IF NOT EXISTS share_access_level VARCHAR(255);

ALTER TABLE legal_tickets
    ADD COLUMN IF NOT EXISTS consultation_fee NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS expert_payment_status VARCHAR(255),
    ADD COLUMN IF NOT EXISTS expert_paid_at TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS commission_rate NUMERIC(5, 4),
    ADD COLUMN IF NOT EXISTS platform_fee NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS expert_payout NUMERIC(19, 2);

CREATE TABLE IF NOT EXISTS revenue_settings (
    id BIGINT PRIMARY KEY,
    commission_rate NUMERIC(5, 4) NOT NULL DEFAULT 0.2000,
    updated_at TIMESTAMP(6),
    updated_by BIGINT
);

-- Some earlier additive migrations used narrower VARCHAR lengths than the
-- default VARCHAR(255) generated by the entity mappings. Widen them without
-- truncating existing values.
ALTER TABLE chat_sessions
    ALTER COLUMN conversation_user_role TYPE VARCHAR(255) USING conversation_user_role::VARCHAR(255),
    ALTER COLUMN conversation_mode TYPE VARCHAR(255) USING conversation_mode::VARCHAR(255),
    ALTER COLUMN share_access_level TYPE VARCHAR(255) USING share_access_level::VARCHAR(255);

ALTER TABLE chat_messages
    ALTER COLUMN resolved_mode TYPE VARCHAR(255) USING resolved_mode::VARCHAR(255);

ALTER TABLE chat_message_feedbacks
    ALTER COLUMN feedback_type TYPE VARCHAR(255) USING feedback_type::VARCHAR(255),
    ALTER COLUMN rating TYPE VARCHAR(255) USING rating::VARCHAR(255);

ALTER TABLE documents
    ALTER COLUMN contract_type TYPE VARCHAR(255) USING contract_type::VARCHAR(255);

ALTER TABLE legal_tickets
    ALTER COLUMN ticket_code TYPE VARCHAR(255) USING ticket_code::VARCHAR(255),
    ALTER COLUMN recipient_type TYPE VARCHAR(255) USING recipient_type::VARCHAR(255),
    ALTER COLUMN priority TYPE VARCHAR(255) USING priority::VARCHAR(255),
    ALTER COLUMN conversation_scope TYPE VARCHAR(255) USING conversation_scope::VARCHAR(255),
    ALTER COLUMN expert_payment_status TYPE VARCHAR(255) USING expert_payment_status::VARCHAR(255);

ALTER TABLE legal_ticket_messages
    ALTER COLUMN sender_role TYPE VARCHAR(255) USING sender_role::VARCHAR(255);

ALTER TABLE conversation_shares
    ALTER COLUMN share_scope TYPE VARCHAR(255) USING share_scope::VARCHAR(255),
    ALTER COLUMN access_mode TYPE VARCHAR(255) USING access_mode::VARCHAR(255);

ALTER TABLE ticket_attachments
    ALTER COLUMN owner_type TYPE VARCHAR(255) USING owner_type::VARCHAR(255),
    ALTER COLUMN scan_status TYPE VARCHAR(255) USING scan_status::VARCHAR(255),
    ALTER COLUMN upload_status TYPE VARCHAR(255) USING upload_status::VARCHAR(255);

ALTER TABLE refund_requests
    ALTER COLUMN account_number TYPE VARCHAR(255) USING account_number::VARCHAR(255),
    ALTER COLUMN invoice_id TYPE VARCHAR(255) USING invoice_id::VARCHAR(255);

ALTER TABLE system_notifications
    ALTER COLUMN type TYPE VARCHAR(255) USING type::VARCHAR(255),
    ALTER COLUMN entity_type TYPE VARCHAR(255) USING entity_type::VARCHAR(255);

UPDATE chat_sessions
SET share_access_level = 'RESTRICTED'
WHERE share_access_level IS NULL;

UPDATE legal_tickets
SET expert_payment_status = 'UNPAID'
WHERE expert_payment_status IS NULL;

ALTER TABLE chat_sessions
    ALTER COLUMN share_access_level SET DEFAULT 'RESTRICTED',
    ALTER COLUMN share_access_level SET NOT NULL;

ALTER TABLE legal_tickets
    ALTER COLUMN expert_payment_status SET DEFAULT 'UNPAID',
    ALTER COLUMN expert_payment_status SET NOT NULL;

-- Hibernate emits CHECK constraints for EnumType.STRING. The two enum fields
-- below were originally added outside the entity baseline and therefore did
-- not receive those constraints.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'chat_sessions'::regclass
          AND conname = 'chat_sessions_share_access_level_check'
    ) THEN
        ALTER TABLE chat_sessions
            ADD CONSTRAINT chat_sessions_share_access_level_check
            CHECK (share_access_level IN ('RESTRICTED', 'PUBLIC')) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'legal_tickets'::regclass
          AND conname = 'legal_tickets_expert_payment_status_check'
    ) THEN
        ALTER TABLE legal_tickets
            ADD CONSTRAINT legal_tickets_expert_payment_status_check
            CHECK (expert_payment_status IN ('UNPAID', 'PENDING', 'PAID')) NOT VALID;
    END IF;
END $$;

ALTER TABLE chat_sessions
    VALIDATE CONSTRAINT chat_sessions_share_access_level_check;

ALTER TABLE legal_tickets
    VALIDATE CONSTRAINT legal_tickets_expert_payment_status_check;

-- The revenue_settings table was present in the baseline before its feature
-- migration added the inline reference, so clean Flyway installs otherwise
-- miss this relationship.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint constraint_row
        JOIN pg_class source_table ON source_table.oid = constraint_row.conrelid
        JOIN pg_class target_table ON target_table.oid = constraint_row.confrelid
        JOIN pg_attribute source_column ON source_column.attrelid = source_table.oid
            AND source_column.attnum = ANY (constraint_row.conkey)
        JOIN pg_attribute target_column ON target_column.attrelid = target_table.oid
            AND target_column.attnum = ANY (constraint_row.confkey)
        WHERE constraint_row.contype = 'f'
          AND source_table.relname = 'revenue_settings'
          AND source_column.attname = 'updated_by'
          AND target_table.relname = 'users'
          AND target_column.attname = 'id'
    ) THEN
        ALTER TABLE revenue_settings
            ADD CONSTRAINT fk_revenue_settings_updated_by
            FOREIGN KEY (updated_by) REFERENCES users(id) NOT VALID;
    END IF;
END $$;

-- Ensure every non-unique index declared directly on a current entity exists.
CREATE INDEX IF NOT EXISTS idx_chat_messages_session_status_created
    ON chat_messages (chat_session_id, status, created_at);

CREATE INDEX IF NOT EXISTS idx_ticket_attachments_owner
    ON ticket_attachments (owner_type, owner_id);

CREATE INDEX IF NOT EXISTS idx_ticket_audit_ticket_created
    ON ticket_audit_logs (ticket_id, created_at);
