CREATE TABLE IF NOT EXISTS ai_query_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    workspace_id VARCHAR(255),
    chat_session_id VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    estimated_tokens INTEGER NOT NULL,
    actual_input_tokens INTEGER,
    actual_output_tokens INTEGER,
    plan_type_snapshot VARCHAR(50),
    context_snapshot_json TEXT,
    error_code VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_ai_query_execution_request UNIQUE (request_id),
    CONSTRAINT fk_ai_query_execution_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_ai_query_execution_user_status_created
    ON ai_query_executions(user_id, status, created_at);

CREATE UNIQUE INDEX IF NOT EXISTS uk_chat_message_request_role
    ON chat_messages(request_id, role)
    WHERE request_id IS NOT NULL;
