spring:
  application:
    name: ai-legal-document-analyzer

  jackson:
    parser:
      allow-unquoted-control-chars: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ai_legal_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

app:
  api:
    callback-base-url: http://localhost:8080

  ai-service:
    base-url: http://localhost:8000

  storage:
    upload-root: uploads

  jwt:
    secret: a-very-secure-secret-key-that-should-be-at-least-256-bits-long-for-hmac-sha-256
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000
    refresh-cookie-name: refreshToken

  payment:
    vnpay:
      pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      return-url: https://factsheet-engaged-upstream.ngrok-free.dev/api/v1/payment-transactions/vnpay-return

      tmn-code: JSLOYW6T
      hash-secret: QPZPU6FGA8L3WXRHEWV1UQHFBHLMWUPP

      version: 2.1.0
      command: pay
      curr-code: VND
      order-type: other
      locale: vn