import { ArrowLeft } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Badge } from "../../components/common/Badge";
import { Button } from "../../components/common/Button";
import { Card } from "../../components/common/Card";
import { PageHeader } from "../../components/common/PageHeader";
import { useToast } from "../../hooks/useToast";
import { approveEarlyPayout, earlyPayoutMoreInfo, getAdminEarlyPayout, markEarlyPayoutPaid, markEarlyPayoutPending, rejectEarlyPayout } from "../../services/revenuePayroll.service";
import type { EarlyPayout } from "../../types/expertRevenue";
import { formatVndCurrency } from "../../utils/format";

export function AdminEarlyPayoutDetailPage(){const {id=""}=useParams();const toast=useToast();const [data,setData]=useState<EarlyPayout|null>(null);const load=useCallback(async()=>{try{setData(await getAdminEarlyPayout(id));}catch(e){toast.error(e instanceof Error?e.message:"Không thể tải yêu cầu");}},[id,toast]);useEffect(()=>{void load();},[load]);const act=async(fn:()=>Promise<unknown>)=>{try{await fn();toast.success("Đã cập nhật yêu cầu");await load();}catch(e){toast.error(e instanceof Error?e.message:"Thao tác thất bại");}};if(!data)return <p>Đang tải...</p>;return <div className="space-y-xl"><Link className="inline-flex items-center gap-xs text-primary" to="/admin/revenue"><ArrowLeft className="h-4 w-4"/>Quay lại doanh thu</Link><PageHeader title={`Ứng doanh thu ${data.requestCode}`} subtitle={`${data.expertName} · kỳ ${data.periodCode}`} actions={<Badge>{data.status}</Badge>}/><div className="grid gap-md md:grid-cols-4"><Metric label="Số tiền yêu cầu" value={data.requestedAmount}/><Metric label="Khả dụng lúc tạo" value={data.eligibleAmountSnapshot}/><Metric label="Khả dụng hiện tại" value={data.currentAvailableAmount}/><Metric label="Được duyệt" value={data.approvedAmount||0}/></div><Card title="Nội dung"><div className="space-y-sm text-sm"><p><b>Lý do:</b> {data.reason}</p><p><b>Ghi chú Expert:</b> {data.expertNote||"-"}</p><p><b>Ghi chú Admin:</b> {data.adminNote||"-"}</p><p><b>Tham chiếu thanh toán:</b> {data.paymentReference||"-"}</p></div></Card><Card title="Thao tác"><div className="flex flex-wrap gap-sm">{["PENDING_ADMIN_REVIEW","EXPERT_RESPONDED"].includes(data.status)&&<><Button onClick={()=>{const raw=prompt("Số tiền duyệt",String(data.requestedAmount));if(raw)void act(()=>approveEarlyPayout(data.id,Number(raw)));}}>Duyệt</Button><Button variant="secondary" onClick={()=>{const note=prompt("Thông tin cần bổ sung");if(note)void act(()=>earlyPayoutMoreInfo(data.id,note));}}>Yêu cầu thêm thông tin</Button><Button variant="danger" onClick={()=>{const reason=prompt("Lý do từ chối");if(reason)void act(()=>rejectEarlyPayout(data.id,reason));}}>Từ chối</Button></>}{data.status==="APPROVED"&&<Button onClick={()=>void act(()=>markEarlyPayoutPending(data.id))}>Chuyển sang chờ thanh toán</Button>}{data.status==="PAYMENT_PENDING"&&<Button onClick={()=>{const ref=prompt("Mã tham chiếu thanh toán");if(ref)void act(()=>markEarlyPayoutPaid(data.id,ref));}}>Đánh dấu đã trả</Button>}</div><p className="mt-md text-xs text-on-surface-variant">Duyệt không đồng nghĩa đã chuyển tiền. Chỉ thao tác “Đánh dấu đã trả” mới tạo payout transaction và trừ số dư statement.</p></Card></div>;}
function Metric({label,value}:{label:string;value:number}){return <Card className="p-md"><p className="text-xs uppercase text-on-surface-variant">{label}</p><p className="mt-xs text-xl font-bold">{formatVndCurrency(Number(value||0),"0 ₫","vi-VN")}</p></Card>;}
